	-- Deleta um usuário.
DELETE * FROM USUARIO WHERE RG = '7110068256';

	-- Deleta todos os usuários.
DELETE * FROM USUARIO;

	-- Deleta um caroneiro.
DELETE * FROM CARONEIRO WHERE RG = '7110068256';

	-- Deleta todos os caroneiros.
DELETE * FROM CARONEIRO;

	-- Deleta um carona.
DELETE * FROM CARONA WHERE RG = '7110068256';

	-- Deleta todos os caronas.
DELETE * FROM CARONA;

	-- Deleta um comentário.
DELETE * FROM COMENTARIO WHERE N_COMENTARIO = 1;

	-- Deleta todos os comentários.
DELETE * FROM COMENTARIO;

	-- Deleta uma região.
DELETE * FROM REGIAO WHERE ID = 1;

	-- Deleta todas as regiões.
DELETE * FROM REGIAO

