	-- Busca um usuário.
SELECT * FROM USUARIO WHERE RG = '7110068256';

	-- Busca todos os usuários.
SELECT * FROM USUARIO;

	-- Busca um caroneiro.
SELECT * FROM CARONEIRO WHERE RG = '7110068256';

	-- Busca todos os caroneiros.
SELECT * FROM CARONEIRO;

	-- Busca um carona.
SELECT * FROM CARONA WHERE RG = '7110068256';

	-- Busca todos os caronas.
SELECT * FROM CARONA;

	-- Busca um comentário.
SELECT * FROM COMENTARIO WHERE N_COMENTARIO = 1;

	-- Busca todos os comentários.
SELECT * FROM COMENTARIO;

	-- Busca uma região.
SELECT * FROM REGIAO WHERE ID = 1;

	-- Busca todas as regiões.
SELECT * FROM REGIAO

